# Generated by Django 4.1 on 2022-09-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(max_length=700)),
                ("shorturl", models.CharField(max_length=100)),
                ("timedatecreated", models.DateTimeField()),
            ],
        ),
    ]
