# Generated by Django 4.1 on 2022-09-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("url_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shorturl",
            old_name="shorturl",
            new_name="short_url",
        ),
    ]
