# Generated by Django 4.1 on 2022-09-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("url_app", "0002_rename_shorturl_shorturl_short_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shorturl",
            old_name="timedatecreated",
            new_name="time_date_created",
        ),
    ]
